### ISSUE TITLE
error in fsharp#Balloon (number must be greater than zero)

### ISSUE THREAD

**Issue by killerswan** [kongo2002/fsharp-vim#2]
I'm using [this commit](https://github.com/killerswan/fsharp-vim/tree/ab4512681881bb21f4e783635dfab0daa6073c63) on [my branch](https://github.com/killerswan/fsharp-vim/commits/master) with merges from various people...

Anyways, when opening a couple *.fsx files (which run fine with F# 3.0) in MacVim (version 7.4b) I see the following:

```
Error detected while processing function fsharp#Balloon:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: number must be greater then zero
```

What's going on, here?
cc @fishman @timrobinson

**Comment by 1tgr** [comment]
This would be the intellisense-style tooltips from [my fork](https://github.com/timrobinson/fsharp-vim) - you're welcome to raise an issue there.

Can you post the minimal F# file that produces the error? Or if you don't care about tooltips, you could turn them off with `set noballooneval`.

**Comment by killerswan** [comment]
I cannot file issues on your fork, for some reason...  (Have GitHub removed this feature?)

And after it seemed so consistent yesterday I'm not seeing it with any of the files I'm opening today after switching back to that same commit. :(

**Comment by killerswan** [comment]
Ahhh, happened again.  Same commit as above, with this file:
https://github.com/killerswan/fsharp-testloop/blob/61af072c80da0c2a0123a4f088aff803ea43b63d/Loop.fsx

**Comment by killerswan** [comment]
Anyways, `set noballooneval` has not fixed this for me.

**Comment by kongo2002** [comment]
As this is an issue with [Tim Robinson's fork](https://github.com/timrobinson/fsharp-vim) I'll close this one here.
